apiVersion: v1
kind: Service
metadata:
  name: i-kube-demo
  namespace: default
  labels:
    app: i-kube-demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: i-kube-demo
